title: Shantanu's wiki
author: Shantanu Mishra
email: hey@8hantanu.net

baseurl: ""
url: "https://8hantanu.net/wiki"

remote_theme: yree/mold

footer_content: >
  ##### Â© 2024 [8hantanu](https://8hantanu.net) | ğŸ“¬ [Comment](javascript:window.location='mailto:hey@8hantanu.net?subject='+encodeURIComponent(document.title)) | â¬…ï¸ [previous](..)

favicon: favicon.ico