title: Shantanu's wiki
author: Shantanu Mishra
email: hey@8hantanu.net

baseurl: ""
url: "https://wiki.8hantanu.net"

remote_theme: yree/mold
footer_content: >
  ##### Â© 2024 [8hantanu](https://8hantanu.net) | ğŸ“œ [Disclaimer](https://8hantanu.net/disclaimer) | ğŸ“¬ [Comment](javascript:window.location='mailto:hey@8hantanu.net?subject='+encodeURIComponent(document.title)) | â¬…ï¸ [go back](..)

favicon: favicon.ico