title: Shantanu's wiki
author: Shantanu Mishra
email: hey@8hantanu.net

url: https://8hantanu.net
baseurl: /wiki

remote_theme: yree/mold

footer_content: >
  [8hantanu](https://8hantanu.net) — [comment](javascript:window.location='mailto:wiki@8hantanu.net?subject='+encodeURIComponent(document.title)) — [previous](..)

favicon: favicon.svg

goat_counter: 8hantanu
